image: library/haskell:latest

stages:
  - debs
  - build
  - test
  - deploy

cache:
    untracked: true
    paths:
    - .stack-work
    - .stack-test
    - "*/stack-work"

debs:
  stage: debs
  script:
    - "stack install yesod-bin --install-ghc"

build:
  stage: build
  script:
    - "stack build"

test:
  stage: test
  script:
    - "stack install hlint"
    - "stack test --flag Owl:library-only --flag Owl:dev"
    - "stack exec -- hlint ."

deploy:
  stage: deploy
  script:
    - "stack exec -- yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags
