image: yufrice/yesod-hlint

stages:
  - build
  - test
  - deploy

cache:
    paths:
    - .stack-work
    - .stack-test

build:
  stage: build
  script:
    - "stack build"

test:
  stage: test
  allow_failure: true
  script:
    - "stack test --flag Owl:library-only --flag Owl:dev"

test-lint:
  stage: test
  allow_failure: true
  script:
    - "hlint ."

deploy:
  stage: deploy
  script:
    - "yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags
