image: yufrice/yesod-hlint

stages:
  - test
  - deploy

cache:
    paths:
    - .stack-work
    - .stack-test

test:
  stage: test
  allow_failure: true
  script:
    - "stack test --flag Owl:library-only --flag Owl:dev"
  except:
    - wip

test-lint:
  stage: test
  allow_failure: true
  script:
    - "stack exec -- hlint ."
  except:
    - wip

deploy:
  stage: deploy
  script:
    - "stack build"
    - "stack exec -- yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags

docker_deploy:
  stage: deploy
  script:
    - stack build --stack-yaml stack-docker.yaml
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE