image: yufrice/yesod-hlint

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
- docker:dind

stages:
  - test
  - deploy

cache:
    paths:
    - .stack-work
    - .stack-test

test:
  stage: test
  allow_failure: true
  script:
    - "stack test --flag Owl:library-only --flag Owl:dev"
  except:
    - wip

test-lint:
  stage: test
  allow_failure: true
  script:
    - "stack exec -- hlint ."
  except:
    - wip

deploy:
  image: yufrice/yesod-keter
  stage: deploy
  script:
    - "stack build"
    - "stack exec -- yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags

services:
- docker:dind

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY

docker_deploy_latest:
  stage: deploy
  image: docker:stable
  script:
    - docker build -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest
  except:
    - tags

docker_deploy:
  stage: deploy
  image: docker:stable
  script:
    - docker build -t $CONTAINER_IMAGE:$CI_BUILD_TAG .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_TAG
  only:
    - tags