image: library/haskell:latest

stages:
  - debs
  - build
  - test
  - deploy

cache:
    paths:
    - .stack-work
    - .stack-test
    - "${CI_PROJECT_DIR}/.stack-work"

  
variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

debs-yesod:
  stage: debs
  script:
    - "stack install yesod-bin --install-ghc"

debs-hlint:
  stage: debs
  script:
    - "stack install hlint --install-ghc"

build:
  stage: build
  script:
    - "stack build"

test:
  stage: test
  allow_failure: true
  script:
    - "stack test --flag Owl:library-only --flag Owl:dev"

test-lint:
  stage: test
  allow_failure: true
  script:
    - "stack exec -- hlint ."

deploy:
  stage: deploy
  script:
    - "stack exec -- yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags
