image: fpco/stack-build

stages:
  - debs
  - build
  - test
  - deploy

debs:
  stage: deps
  script:
    - "stack install yesod-bin --install-ghc"

build:
  stage: build
  script:
    - "stack build"

test:
  stage: test
  script:
    - "stack test --flag Owl:library-only --flag Owl:dev"
    - "stack exec -- hlint ."

deploy:
  stage: deploy
  script:
    - "stack exec -- yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags
