image: yufrice/yesod-hlint

stages:
  - test
  - deploy

cache:
    paths:
    - .stack-work
    - .stack-test

test:
  stage: test
  allow_failure: true
  script:
    - "stack test --flag Owl:library-only --flag Owl:dev"
  except:
    - wip

test-lint:
  stage: test
  allow_failure: true
  script:
    - "stack exec -- hlint ."
  except:
    - wip

deploy:
  image: yufrice/yesod-keter
  stage: deploy
  script:
    - "stack build"
    - "stack exec -- yesod keter"
  artifacts:
    paths:
      - Owl.keter
  only:
    - tags

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY

docker_deploy_latest:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY:latest .
    - docker push "$CI_REGISTRY_IMAGE"
  except:
    - tags

docker_deploy:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY:$CI_BUILD_TAG .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - tags