version: '3'

services:

  yesod:
    container_name: yesodServer
    env_file:
      - .env
    build:
      context: ./docker/webserver
      dockerfile: Dockerfile
      args:
        - GitLab_Token=${GitLab_Token}
        - ReleaseVer=${ReleaseVer}
    ports:
      - "8484:8484"