version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_USERNAME: Owl
      MONGO_PASS: Owl
      MONGO_INITDB_DATABASE: Owl
    volumes:
      - ./docker/database/init.js:/docker-entrypoint-initdb.d/init.js

  db-express:
    image: mongo-express
    restart: always
    depends_on:
        - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_BASICAUTH_USERNAME: User
      ME_CONFIG_BASICAUTH_PASSWORD: Pass

  yesod:
    container_name: yesodServer
    env_file:
      - .env
    build:
      context: ./docker/webserver
      dockerfile: Dockerfile
      args:
        - GitLab_Token=${GitLab_Token}
        - ReleaseVer=${ReleaseVer}
    depends_on:
      - mongo
    ports:
      - "8484:80"
